# Discord bot token
token: ""

# Guild & channel ids to join. Add them in pair, separated by a comma
guild: ""
channel: ""

# User ids that can add song and restart the bot. Separate multiple ids by comma
admin: ""
